### ISSUE TITLE
Error running snaptools snap-pre

### ISSUE THREAD

**Issue by Austin-s-h** [r3fang/SnapTools#15]
Hi! I'm trying to generate a snapfile, but I am running into the following error. Could you provide guidance as to why this may be happening? Thanks!
Here is my command 
```
snaptools snap-pre  \
	--input-file 4_subsampled.HH8.filtered.tagged.Aligned.out.renamed.sorted.bam \
	--output-snap 4_subsampled.HH8.filtered.tagged.Aligned.out.renamed.snap  \	
	--genome-name galGal5 \
	--genome-size chick_chrNameLength.chrom.size  \
	--barcode-file sciATACchick.barcodes.txt \
	--min-mapq 30  \
	--min-flen 0  \
	--max-flen 1500  \
	--keep-chrm True  \
	--keep-single True  \
	--keep-secondary False  \
	--overwrite True  \
	--max-num 1000000  \
	--qc-file True \
	--verbose True
```
My bamfile looks like this...
```
@HD	VN:1.4
@SQ	SN:chr10	LN:21119840
@SQ	SN:chr11	LN:20200042
@SQ	SN:chr12	LN:20387278
@SQ	SN:chr13	LN:19166714
@SQ	SN:chr14	LN:16219308
@SQ	SN:chr15	LN:13062184
@SQ	SN:chr16	LN:2844601
@SQ	SN:chr17	LN:10762512
@SQ	SN:chr18	LN:11373140
@SQ	SN:chr19	LN:10323212
@SQ	SN:chr1	LN:197608386
@SQ	SN:chr20	LN:13897287
@SQ	SN:chr21	LN:6844979
@SQ	SN:chr22	LN:5459462
@SQ	SN:chr23	LN:6149580
@SQ	SN:chr24	LN:6491222
@SQ	SN:chr25	LN:3980610
@SQ	SN:chr26	LN:6055710
@SQ	SN:chr27	LN:8080432
@SQ	SN:chr28	LN:5116882
@SQ	SN:chr2	LN:149682049
@SQ	SN:chr30	LN:1818525
@SQ	SN:chr31	LN:6153034
@SQ	SN:chr32	LN:725831
@SQ	SN:chr33	LN:7821666
@SQ	SN:chr3	LN:110838418
@SQ	SN:chr4	LN:91315245
@SQ	SN:chr5	LN:59809098
@SQ	SN:chr6	LN:36374701
@SQ	SN:chr7	LN:36742308
@SQ	SN:chr8	LN:30219446
@SQ	SN:chr9	LN:24153086
@SQ	SN:chrM	LN:16775
@SQ	SN:chrW	LN:6813114
@SQ	SN:chrZ	LN:82529921
@PG	ID:STAR	PN:STAR	VN:2.7.0f_0328	CL:STAR   --runThreadN 20   --genomeDir /workdir/rs958/programs/STAR/galgal6   --readFilesType SAM   SE      --readFilesIn /workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8aa.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ab.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ac.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ad.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ae.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8af.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ag.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ah.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ai.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8aj.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ak.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8al.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8am.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8an.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ao.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ap.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8aq.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ar.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8as.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8at.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8au.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8av.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8aw.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ax.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ay.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8az.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ba.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8bb.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8bc.filtered.tagged.bam      --readFilesCommand samtools   view   -@   2      --outFileNamePrefix /workdir/rs958/20190907_sciSeqTest/galgal6/HH8.filtered.tagged.   --outStd SAM   --outSAMtype SAM      --outSAMunmapped Within      --outSAMmultNmax 1   --outFilterMultimapNmax 50   --sjdbGTFfile /workdir/rs958/programs/STAR/galgal6/galGal6.refGene.gtf   --sjdbOverhang 49
@CO	user command line: STAR --readFilesCommand samtools view -@ 2 --outSAMmultNmax 1 --outFilterMultimapNmax 50 --outSAMunmapped Within --outSAMtype SAM --outStd SAM --genomeDir /workdir/rs958/programs/STAR/galgal6 --sjdbGTFfile /workdir/rs958/programs/STAR/galgal6/galGal6.refGene.gtf --runThreadN 20 --readFilesIn /workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8aa.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ab.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ac.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ad.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ae.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8af.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ag.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ah.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ai.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8aj.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ak.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8al.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8am.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8an.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ao.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ap.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8aq.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ar.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8as.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8at.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8au.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8av.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8aw.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ax.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ay.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8az.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8ba.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8bb.filtered.tagged.bam,/workdir/rs958/20190907_sciSeqTest/galgal6/zUMIs_output/.tmpMerge//HH8.HH8bc.filtered.tagged.bam --outFileNamePrefix /workdir/rs958/20190907_sciSeqTest/galgal6/HH8.filtered.tagged. --sjdbOverhang 49 --readFilesType SAM SE
AACTTGATGCGTGCTAGTAGGAAGGACGAT-ATTTACAC:NB500947:861:H3HWFBGXC:1:11101:9731:9824	4	*	0	0	*	*	0	0	CCTGTACACCTGATTGCCAGAAGAGGGCATCAGATCCCTTTATAGATGGT	AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE	NH:i:0	HI:i:0	AS:i:18	nM:i:0	uT:A:1	BX:Z:AACTTGATGCGTGCTAGTAGGAAGGACGAT	BC:Z:AACTTGATGCGTGCTAGTAGGAAGGACGAT
GAGAGCTCTAGCCACACTGTACATACCGCT-AGACTAAT:NB500947:861:H3HWFBGXC:1:11101:15942:9826	16	chr7	11274343	255	50M	*	0	0	CTGTGGTAGCCCAGAGGTCTCCCCAGCAGATGTTCTCTCCTACTTTAGGT	EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA	NH:i:1	HI:i:1	AS:i:49	nM:i:0	BX:Z:GAGAGCTCTAGCCACACTGTACATACCGCT	BC:Z:GAGAGCTCTAGCCACACTGTACATACCGCT
ATTCATCTTGTTCTGCCGTCGCACAGTGTA-TTGAAGCG:NB500947:861:H3HWFBGXC:1:11101:14639:9832	16	chr1	55776983	255	50M	*	0	0	CCAATGGTGAGATGCTTGCTAGTGGTTGCAACCCTTGGCTGGGGTTCACC	EEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEAEEEEEEEEE6AAAAA	NH:i:1	HI:i:1	AS:i:49	nM:i:0	BX:Z:ATTCATCTTGTTCTGCCGTCGCACAGTGTA	BC:Z:ATTCATCTTGTTCTGCCGTCGCACAGTGTA
TTACACAACATGCGGTTTGATACCACACAA-GTCTTTAT:NB500947:861:H3HWFBGXC:1:11101:25172:9840	16	chr1	88366497	255	50M	*	0	0	CCTCATTTGTCAACGGGTACATGCTGACAGAATAGCCAAGCATTTTGTGG	EEEEEEEEEEEEEEAEE/EEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA	NH:i:1	HI:i:1	AS:i:49	nM:i:0	BX:Z:TTACACAACATGCGGTTTGATACCACACAA	BC:Z:TTACACAACATGCGGTTTGATACCACACAA
TATCTACGCGTGCGTGGCGACACGCTAATG-GCAGCGAA:NB500947:861:H3HWFBGXC:1:11101:8819:9841	16	chr1	20360291	255	48M2S	*	0	0	GCTCTGAGCTAGGATCTGCAAAGACAGCTGGGCCTGCCTTTGTCCTGAAG	EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA	NH:i:1	HI:i:1	AS:i:47	nM:i:0	BX:Z:TATCTACGCGTGCGTGGCGACACGCTAATG	BC:Z:TATCTACGCGTGCGTGGCGACACGCTAATG
AACTTGATGCCTGGTTACTTCAAGTCACCA-ACTAAAGG:NB500947:861:H3HWFBGXC:1:11101:6519:9847	16	chr11	8646791	255	50M	*	0	0	CTAACGTCTTCATTAGTGCCATAATACCAGCTAAGAAAACTCTCCTGGCC	EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA	NH:i:1	HI:i:1	AS:i:49	nM:i:0	BX:Z:AACTTGATGCCTGGTTACTTCAAGTCACCA	BC:Z:AACTTGATGCCTGGTTACTTCAAGTCACCA
TGGAGCAATTTCGTGACCGCAGAGCGTACG-TATATTCC:NB500947:861:H3HWFBGXC:1:11101:1364:9862	4	*	0	0	*	*	0	0	GTACACTTACTACAAAGAAGATTATCTGAAATACTCCCCACTGGCTCCTT	AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAEAEEEEEEEEE	NH:i:0	HI:i:0	AS:i:19	nM:i:0	uT:A:1	BX:Z:TGGAGCAATTTCGTGACCGCAGAGCGTACG	BC:Z:TGGAGCAATTTCGTGACCGCAGAGCGTACG
TATCTACGCGGTCTGAAGAGTGCGGAGAGA-TCCCTTGA:NB500947:861:H3HWFBGXC:1:11101:9472:9885	0	chr10	6810885	255	50M	*	0	0	GGAGTGATCTGTCTGTTAGCCTGCAGGTACTTACTGGTCTCACAGCAAGA	AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE/EEEEEEEE	NH:i:1	HI:i:1	AS:i:49	nM:i:0	BX:Z:TATCTACGCGGTCTGAAGAGTGCGGAGAGA	BC:Z:TATCTACGCGGTCTGAAGAGTGCGGAGAGA
```

And the error I'm getting
```

Traceback (most recent call last):
  File "/usr/local/bin/snaptools", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/snaptools/bin/snaptools", line 38, in <module>
    parse_args()    
  File "/opt/snaptools/snaptools/parser.py", line 144, in parse_args
    verbose=args.verbose)
  File "/opt/snaptools/snaptools/snap_pre.py", line 364, in snap_pre
    if barcode not in barcode_dict: continue  
UnboundLocalError: local variable 'barcode' referenced before assignment
error: unable to read genome information
```

**Comment by r3fang** [comment]
what’s the version of snap tools?

--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego

**Comment by Austin-s-h** [comment]
I'm running version 1.4.8

**Comment by JiaqiLi1024** [comment]
I solved this problem by adding `barcode = None` at line 281 in snap_pre to init barcode variable
hope it will be helpful
