### ISSUE TITLE
Error in making snap object

### ISSUE THREAD

**Issue by seishin0125** [r3fang/SnapTools#4]
Hi!
I tried to make snap object from my own aligned BED file by snaptools 1.4.3.

snaptools snap-pre --input-file=snaptools_input_sorted.bed --output-snap=out.snap --genome-name=mm10 --genome-size=mm10.chrom.sizes --min-mapq=0 --min-flen=0 --max-flen=2000 --keep-chrm=False --keep-single=TRUE --keep-secondary=False --overwrite=True --verbose=True

However, error messages were generated.
Traceback (most recent call last):
  File "/home/ATAC-seq/snaptools/bin/snaptools", line 38, in <module>
    parse_args()
  File "/yshare1/home/ATAC-seq/snaptools/snaptools/parser.py", line 144, in parse_args
    verbose=args.verbose)
  File "/yshare1/home/ATAC-seq/snaptools/snaptools/snap_pre.py", line 224, in snap_pre
    barcode_dict = snaptools.snap.getBarcodesFromInput(input_file, file_format);
  File "/yshare1/home/ATAC-seq/snaptools/snaptools/snap.py", line 174, in getBarcodesFromInput
    return getBarcodesFromBed(fname);
  File "/yshare1/home/ATAC-seq/snaptools/snaptools/snap.py", line 251, in getBarcodesFromBed
    barcode_dict[barcode.decode()] = i
AttributeError: 'str' object has no attribute 'decode'

I'm afraid that this is due to the format of  barcode sequences. (Barcodes were already converted into cellname.)
Are there any requirements for the style of barcode sequence?

head snaptools_input_sorted.bed
chr1    10039996        10040196        20dpc_1
chr1    10056636        10056836        20dpc_1
chr1    101693776       101693968       20dpc_1
chr1    104005976       104006168       20dpc_1
chr1    104999360       104999568       20dpc_1
chr1    105355968       105356176       20dpc_1
chr1    105488400       105488608       20dpc_1
chr1    105648432       105648624       20dpc_1
chr1    106063264       106063464       20dpc_1
chr1    106176808       106177008       20dpc_1
(This bedfile is sorted by the name of column 4.)

**Comment by r3fang** [comment]
which python version are you using?

**Comment by seishin0125** [comment]
I use Python 3.6.4

**Comment by seishin0125** [comment]
I found that if the line 251 in "snap.py" was changed to
barcode_dict[barcode] = i
Snaptools did not displayed the error message.

**Comment by seishin0125** [comment]
Again, I tried to run the code below, error messages were generated.
$ snaptools snap-add-gmat --snap-file=out.snap --gene-file=/home/username/Index/gene_vM20_coding.bed

Traceback (most recent call last):
  File "/home/username/snaptools/bin/snaptools", line 38, in <module>
    parse_args()
  File "/yshare1/home/username/snaptools/snaptools/parser.py", line 184, in parse_args
    verbose=args.verbose)
  File "/yshare1/home/username/snaptools/snaptools/add_gmat.py", line 138, in snap_gmat
    dump_read(snap_file, fout_frag.name, buffer_size, None, tmp_folder, True);
  File "/yshare1/home/username/snaptools/snaptools/snap.py", line 839, in dump_read
    fout.write(("\t".join(map(bytes, item)) + "\n").encode())
TypeError: string argument without an encoding

This error was resolved when the line 838 in snap.py was changed to
"fout.write(("\t".join([str(i) for i in item]) + "\n"))"

**Comment by r3fang** [comment]
Hi can you update snaptools to the latest version 1.4.4 and try it again? Bugs should be fixed in the latest version.

**Comment by seishin0125** [comment]
I confirmed that the error was fixed! Thank you so much!!
