### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by smanne07** [r3fang/SnapTools#8]
Hi ,
I am using python 3.6.3 and installed snaptools and i am getting the following error

`Traceback (most recent call last):
  File "/home/sasim/my_python-3.6.3/bin/snaptools", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/sasim/tools/snaptools/bin/snaptools", line 36, in <module>
    from snaptools.parser import parse_args
  File "/home/sasim/tools/snaptools/snaptools/parser.py", line 31, in <module>
    from snaptools.utilities import str2bool
  File "/home/sasim/tools/snaptools/snaptools/utilities.py", line 7, in <module>
    import pybedtools
  File "/home/sasim/my_python-3.6.3/lib/python3.6/site-packages/pybedtools/__init__.py", line 17, in <module>
    from .bedtool import BedTool
  File "/home/sasim/my_python-3.6.3/lib/python3.6/site-packages/pybedtools/bedtool.py", line 388, in <module>
    class BedTool(object):
  File "/home/sasim/my_python-3.6.3/lib/python3.6/site-packages/pybedtools/bedtool.py", line 1637, in BedTool
    @_wraps(prog='bed12ToBed6', implicit='i', bam=None, other=None)
  File "/home/sasim/my_python-3.6.3/lib/python3.6/site-packages/pybedtools/bedtool.py", line 167, in _wraps
    p = subprocess.Popen(helpers._version_2_15_plus_names(prog) + ['-h'],
  File "/home/sasim/my_python-3.6.3/lib/python3.6/site-packages/pybedtools/helpers.py", line 287, in _version_2_15_plus_names
    _check_for_bedtools()
  File "/home/sasim/my_python-3.6.3/lib/python3.6/site-packages/pybedtools/helpers.py", line 87, in _check_for_bedtools
    vv = v.decode().split('v')[1]
IndexError: list index out of range`

Can you help me in troubleshooting what may be causing this error?

Thank you
Sasi

**Comment by r3fang** [comment]
hi Sasi,

This is an error caused by failure of installing pybedtools. Can you try to pre-install pybedtools? and let me know if this is not working

Best,
-R

**Comment by smanne07** [comment]
Sure i will reinstall pybedtools and see how it goes.

Thank you

**Comment by smanne07** [comment]
Following this solution here https://github.com/r3fang/SnapATAC/issues/2 worked!

Thanks again!
